### PR TITLE
Feature/tests

### PR DESCRIPTION
**Pull request by swift-student**
## What's here (& why)
- Delete broken tests from my last PR (whoops)
- Expand GraphQL Tests
- Move live GraphQL Tests to AsynchronousTests bundle
- Add user defaults tests

### CODE REVIEW

**Comment by jonbash** [comment]
Hard to tell since there's a ton of file changes for some reason....??? Seems like duplicated changes from previous PRs or something. Not sure what's going on there... Worth looking into. 😅 But from your description it sounds like fine changes!

**Review by DeVitoC — APPROVED** [review]
Looks ok from what I can tell.

**Comment by swift-student** [comment]
> Hard to tell since there's a ton of file changes for some reason....??? Seems like duplicated changes from previous PRs or something. Not sure what's going on there... Worth looking into. 😅 But from your description it sounds like fine changes!

Yeah, I just needed to merge Master in again, apparently. Still 23 files changed, but a lot better..

**Review by jonbash — APPROVED** [review]
Much better! All looks good from here.

**Pull request merged**
